### ISSUE TITLE
ADD GUITARHEROSTYLES, YOU

### ISSUE THREAD

**Issue by fanofbillgates** [LXanii/GD-YouTubers#16]
WHY DID YOU ADDED CRAZEN AND OTHER NONAME YOUTUBERS BUT NOT GUITAR YOU!!! ADD GUITARHEROSTYLES AND FIX SOULSTRK PROFILE OR ELSE FOR WHAT I DOWNLOADED THIS MOD?

**Comment by LXanii** [comment]
added souls trk, but no rapist
