### ISSUE TITLE
bro really

### ISSUE THREAD

**Issue by zohnannor** [LXanii/GD-YouTubers#3]
https://github.com/LXanii/GD-YouTubers/blob/c7d466378f82c81a53a91ac2f673bfbc3c48395f/src/main.cpp#L21

web request each time profile page is opened?

unless it's intentional, use this instead: https://docs.geode-sdk.org/mods/resources#adding-audio-other-files

cool mod otherwise :)

<details>
<summary>Details</summary>

:trollface: 

</details>

**Comment by LXanii** [comment]
Take another look at the code please before making comments like this.

**Comment by zohnannor** [comment]
OMG I am so ashamed I didn't notice `if (!downloaded)` literally one line above... I'm terribly sorry for this. Honestly how am I so stupid.

Though I still think this method is not optimal. You could instead have a static array (~~or even better -- a hashset~~ apparently I am ~~really dumb~~ not used to C++ code!) of player's IDs and then check if viewed player's ID is in it. This way:

1) You don't need to do any web requests and download files on each game startup (see I got it this time :) )
2) The IDs are constant, but nicknames are not (tomorrow one of the people changes their nickname and it's over)
2.1) 👆 and therefore will not require you to update the mod.
3) Possibly change a set into a map with YouTube links and make the icon clickable?

**Comment by zohnannor** [comment]
Sorry again for my stupidity, the issue can be closed.
