### ISSUE TITLE
idk if bug

### ISSUE THREAD

**Issue by Helloausername** [LXanii/GD-YouTubers#6]
![Screenshot_20240219-174044_Geode](https://github.com/LXanii/GD-YouTubers/assets/158708969/585f8132-c23f-4e6e-9bee-20b012181d81)
the badge is behind the text

**Comment by KontrollFreek** [comment]
![image](https://github.com/LXanii/GD-YouTubers/assets/72424960/ede24b1c-c1cb-4f43-8d19-fdb7131749cf)
also does this (i assume) because of betteredit
